baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Vite Server Test'
primary: true
siteGroup: 861e167e-8a7c-45ee-84d8-e7ac3471816f # Craft Vite Server Test
sortOrder: 1
